steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'bigquery/job_container/Dockerfile'
      - '-t'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/bigquery-sync/bigquery-sync-job:$BUILD_ID'
      - '-t'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/bigquery-sync/bigquery-sync-job:latest'
      - '.'

  # Push Docker image to Artifact Registry
  - id: 'push-image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/bigquery-sync/bigquery-sync-job'

  # Deploy to Cloud Run Job
  - id: 'deploy-job'
    name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['push-image']
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'bigquery-sync-job'
      - '--image=europe-west3-docker.pkg.dev/$PROJECT_ID/bigquery-sync/bigquery-sync-job:$BUILD_ID'
      - '--region=europe-west3'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID,GCS_BUCKET_NAME=nvidia-blogs-raw,BIGQUERY_DATASET=nvidia_blog,EMBEDDING_MODEL=text-multilingual-embedding-002,EMBEDDING_REGION=us-central1'
      - '--service-account=56324449160-compute@developer.gserviceaccount.com'
      - '--cpu=2'
      - '--memory=1Gi'
      - '--max-retries=1'
      - '--task-timeout=3600'
      - '--project=$PROJECT_ID'

images:
  - 'europe-west3-docker.pkg.dev/$PROJECT_ID/bigquery-sync/bigquery-sync-job:$BUILD_ID'
  - 'europe-west3-docker.pkg.dev/$PROJECT_ID/bigquery-sync/bigquery-sync-job:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
